### ISSUE TITLE
Add CI support?

### ISSUE THREAD

**Issue by mnquintana** [atom/flight-manual.atom.io#101]
Without knowing too much about the asciidoc build process on Atlas, I'm wondering if it would be worth adding some basic CI support to prevent things like broken links, typos, and broken downloads / exports. Maybe we could run a test suite on Travis and test builds on Atlas to catch things like this before merging PRs?

/cc @atom/issue-triage @schacon

**Comment by gjtorikian** [comment]
Added via https://github.com/atom/flight-manual.atom.io/pull/158.
