### ISSUE TITLE
figlet bug on Ubuntu in Chapter 3 - Hacking Atom

### ISSUE THREAD

**Issue by UsabilityEtc** [atom/flight-manual.atom.io#104]
When I created the [modifying text package](https://atom.io/docs/v1.0.3/hacking-atom-package-modifying-text) in Chapter 3 on Ubuntu 12.04 with Node.js 0.12.7, [figlet](https://www.npmjs.com/package/figlet) 1.0.8 (and 1.1.1) produced an error saying that the font o8 couldn't be found. It seems that figlet on Ubuntu needs the first letter of the font name to be capitalised: O8 works on Ubuntu whereas o8 doesn't.

I've created the modifying text package on Windows 7 and OS X Yosemite (both with Node.js 0.12.7 and figlet 1.0.8) and didn't get an error when I used the o8 font.

A simple fix for this is to change o8 to O8 in the example as O8 seems to work on all platforms.

**Comment by lee-dohm** [comment]
Fixed in #234.
