### ISSUE TITLE
Error in EPUB file

### ISSUE THREAD

**Issue by makenova** [atom/flight-manual.atom.io#107]
According to this [EPUB verification site](http://validator.idpf.org/) there are errors in the EPUB file. I discovered this after I tried to upload it to my Google Play Books Library.
![screencapture-validator-idpf-org-application-validate](https://cloud.githubusercontent.com/assets/941708/9116741/8ce490d2-3c2b-11e5-8f8e-1d83f525b78b.png)

**Comment by makenova** [comment]
I tried building the books myself to see if I could fix the issues but as I don't write any ruby, I ran into some unrelated dependency issues really quick. Sorry I couldn't be more helpful.

**Comment by gjtorikian** [comment]
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed in that we no longer support ePub for now.
