### ISSUE TITLE
docs for 1.0.5 not shown

### ISSUE THREAD

**Issue by palango** [atom/flight-manual.atom.io#111]
When I visit https://atom.io/docs/v1.0.5/ I dont get any docs shown. https://atom.io/docs/v1.0.4/ however works fine.

**Comment by thomasjo** [comment]
Thanks for the heads up! /cc @thedaniel

**Comment by thedaniel** [comment]
@schacon do you have a minute to look at why the last set of docs wasn't generated?

**Comment by lee-dohm** [comment]
This is persistent, v1.0.6 and v1.0.7 are also blank.

**Comment by thedaniel** [comment]
The latest docs are fixed, I'll close this when I import the docs for 5 & 6.

**Comment by 50Wliu** [comment]
1.0.5 and 1.0.6 work for me now.
