### ISSUE TITLE
Getting Started overwritten with appendix in TOC

### ISSUE THREAD

**Issue by sergey-salnikov** [atom/flight-manual.atom.io#121]
"Getting Started" link on https://atom.io/docs points to https://atom.io/docs/v1.0.9/upgrading-to-1-0-apis-upgrading-your-package. And in the sidebar in the manual itself sections 1.1 through 1.3 are overwritten with sections from appendix.

Appendix subsections are labelled "A1.1" and so on in 1.0.4, both in the sidebar and in the top of the page. And in 1.0.7 and later there is just "1.1" without the "A".

**Comment by izuzak** [comment]
Thanks for reporting this -- yeah, that looks broken, sorry! We'll try to get that fixed as soon as possible. In the meantime, you can read the content in this repository.

**Comment by izuzak** [comment]
cc @thedaniel

**Comment by apjanke** [comment]
Hi folks. I ran in to this and reported it as a separate bug on the main atom repo. Bringing it over here as a detailed example of what's happening.

---------------------------------

On the main Flight Manual table of contents at https://atom.io/docs/v1.0.19/, it lists the following subsections in chapter 1.

Chapter 1: Getting Started
    1.1 Why Atom
    1.2 Installing Atom
    1.3 Atom Basics
    1.4 Summary

<img width="522" alt="screen shot 2015-10-16 at 12 40 06 am" src="https://cloud.githubusercontent.com/assets/2618447/10533989/95ea6ada-739e-11e5-8e73-33119115b06f.png">

But once I click on one of those to get [in to Chapter 1](https://atom.io/docs/v1.0.19/getting-started-why-atom), the navigation sidebar on the left shows a different set of sections.

1 : Getting Started
    1.1 Upgrading Your Package
    1.2 Upgrading Your UI Theme Or Package Selectors
    1.3 Upgrading Your Syntax Theme
    1.4 Summary

<img width="669" alt="screen shot 2015-10-16 at 12 41 57 am" src="https://cloud.githubusercontent.com/assets/2618447/10533995/b8a5e18a-739e-11e5-9627-aa100ddf4f9a.png">

If I click on one of those, it seems to pull up old documentation. For example, the 1.1 "Upgrading Your Package" section starts out like this:

> Atom is rapidly approaching 1.0. Much of the effort leading up to the 1.0 has been cleaning up APIs in an attempt to future proof,

The prev / next links at the bottom of the pages still seem to work and get to the current docs, though.

**Comment by apjanke** [comment]
I tried to reproduce this by checking out atom/docs and doing the build. But the HTML output it produces is a single file, and not the per-chapter pages that are on the web site. Is there a way to build the multi-page website version of the documentation from this repo?

**Comment by gjtorikian** [comment]
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed.
