### ISSUE TITLE
Typo in a link near the bottom of Section 3.2: The Init File

### ISSUE THREAD

**Issue by terrycloth** [atom/flight-manual.atom.io#123]
In the first sentence of the last paragraph:

> Now, reload Atom and use the **[Section 1-9](https://atom.io/docs/latest/1-introduction/_command_palette)** to execute 
> the new command by name (i.e., "Markdown: Paste As Link").

I believe it should should say "...and use the *command palette* to execute..." instead. Also, the link is broken, and the URL it points to returns a 404 error.

**Comment by gjtorikian** [comment]
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed.
