### ISSUE TITLE
TextEditorElement 404s

### ISSUE THREAD

**Issue by 50Wliu** [atom/flight-manual.atom.io#128]
https://atom.io/docs/api/v1.7.2/TextEditorElement
Accessed from this page (introductory paragraph): https://atom.io/docs/api/v1.7.2/TextEditor

Edit 4/19/2016: TextEditorView has been renamed to TextEditorElement, but still 404s.

**Comment by MaximSokolov** [comment]
`TextEditorView` is deprecated ([text-editor-view.coffee#L9](https://github.com/atom/atom/blob/b4dfb2a31b4688e295d2e85a1b4660909e188029/src/text-editor-view.coffee#L9)):

> **Deprecated**: Represents the entire visual pane in Atom.

Should be link to [`ViewRegistry`](https://atom.io/docs/api/v1.0.19/ViewRegistry) instead
