### ISSUE TITLE
Confusion from a non-programmer

### ISSUE THREAD

**Issue by AddemF** [atom/flight-manual.atom.io#147]
At the request of someone on the forums, in response to a question about easier guides to read about Atom, I'm posting a few things from the guide that I don't understand.  Basically I don't understand anything at all from the guide, perhaps because I don't have a Computer Science background, but for specificity here are some examples.  

First, in the first paragraph it mentions an API and I don't know what that is.  I continued reading anyway, hoping it wouldn't matter--and I think I was right, but just heads-up that this is already looking bad for my comprehension.

The first section is about upgrading and not actually acquiring and installing the software, which seems like that would actually be where you get started, but I've done that part myself no problem, so moving on then.

In the sentence from the first section of the first section of the "Getting Started" section,

> We’ve set deprecation messages and errors in strategic places to help make sure you don’t miss anything.

I don't know what deprecation messages are though I'm guessing they're notes about which kinds of commands you are encouraging people not to use any more.

In the sentence 

> If you use any class from require 'atom' with a $ or View in the name, add the atom-space-pen-views module to your package’s package.json file’s dependencies:

Things get rough for me here.  I know what a class is in Python, but I don't know what that means in this context since I didn't think I was programming yet.  I don't know how to add a module to anything, I don't know what my package is (I know what a package is mostly, but "my package"?  Is that all of Atom?  Is there a package called 'atom'?  Do I need to know this stuff?), I don't know what my package's 'package.json' is or how to learn anything about its file dependencies.  

And it's about at this point that I realize I'm in way over my head and need to figure this stuff out some other way.

**Comment by 50Wliu** [comment]
Yeah, Chapter 1 in the Flight Manual seems incorrect at this point.  It should be introducing the reader to Atom, not telling them how to fix deprecated packages.

**Comment by lee-dohm** [comment]
Thanks @AddemF :grinning:

**Comment by 50Wliu** [comment]
I believe this has been fixed with the transition to nanoc.
