### ISSUE TITLE
Docs pretend issue #11 doesn't exist

### ISSUE THREAD

**Issue by lee-dohm** [atom/flight-manual.atom.io#153]
_From @OJFord on January 4, 2016 19:15_

The [documentation describes changing spell-check language](https://atom.io/docs/v1.3.2/using-atom-writing-in-atom#spell-checking), but we know this isn't possible/doesn't work, as discussed in atom/spell-check#11.

Furthermore, that discussion is locked until "someone starts working on [it]", and has been since August 2015. This being a pretty long-lived (and with no end in sight) bug/missing feature, it seems beyond misleading to describe "how to" change spell-check language in docs.

Obviously everyone's preferred solution is to fix atom/spell-check#11, but until that's done, this description should be removed from the guide.

_Copied from original issue: atom/spell-check#101_

**Comment by OJFord** [comment]
Whoops, sorry for posting in spell-check, wasn't thinking.

**Comment by lee-dohm** [comment]
It's quite alright! Just remember to subscribe here for updates :grinning:
