### ISSUE TITLE
Flight Manual "Getting Started" chapter links to wrong document on docs site

### ISSUE THREAD

**Issue by derelk** [atom/flight-manual.atom.io#155]
The Atom Flight Manual link to "Getting Started" on https://atom.io/docs actually links to https://atom.io/docs/v1.3.2/upgrading-to-1-0-apis-upgrading-your-package, which is a completely different document (Upgrading to 1.0 APIs). Even if you manage to make it into the actual Flight Manual, all of the chapter 1 TOC is still from Upgrading to 1.0 APIs.

**Comment by derelk** [comment]
![image](https://cloud.githubusercontent.com/assets/1585343/12159948/fa5ccad8-b49b-11e5-8bcb-662b9fda2eb3.png)

**Comment by mnquintana** [comment]
It does indeed – thanks for the report!

**Comment by derelk** [comment]
Just saw this still hasn't been fixed and wanted to bump. I really can't underscore enough what a terrible experience this is for a new user. You've just installed Atom and go to the main docs page to learn the basics, and instead you're dropped into "Use atom-space-pen-views" and a bunch of other stuff that's nonsense to you. Even when you've realized you're not in the right place, it's not easy to find the correct link to the actual Getting Started section.

**Comment by Daedalustx** [comment]
Super confusing!!

**Comment by gjtorikian** [comment]
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed.
