### ISSUE TITLE
Use consistent ordering of modifier keys in key bindings stated in the Flight Manual

### ISSUE THREAD

**Issue by WalterGR** [atom/flight-manual.atom.io#161]
I'd love to see command names listed in the Flight Manual to make it possible/easier to find the appropriate documentation (#160 - "Request: Include command names in the manual").

Currently the way to work around the command names not being listed is to search the Flight Manual for the default key binding of the command you want to look up.

This is made more difficult because the modifier keys aren't always presented in a consistent order.  This means that, to look up a documentation for a command, you have to map the command to the default key binding and then search for every combination of orderings of modifier keys.

For example, `ctrl` appears before `cmd` in

`ctrl-cmd-m  Select all the text inside the current brackets`

but after `cmd` in

`You can view all of Atom’s UI components by opening the styleguide: open the command palette (cmd-shift-P) and search for styleguide, or just type cmd-ctrl-shift-G.`

`alt` appears before `ctrl` in

`Once you’ve got your test suite written, you can run it by pressing cmd-alt-ctrl-p`

 But after `ctrl` in

`Run the command “Window: Reload” from the command palette or by pressing ctrl-alt-cmd-l`

etc.

**Comment by lee-dohm** [comment]
The OS X Human Interface Guidelines always order them as Control&rarr;Option/Alt&rarr;Shift&rarr;Command/Super

**Comment by 50Wliu** [comment]
I agree: for other platforms the rule seems to be the same (Control + Alt + Shift + Key).

We should also update Atom's keybindings, which currently show Shift as the first modifier I believe.

**Comment by lee-dohm** [comment]
And personally, I like using the `kbd` tag to mark them like so: <kbd>Cmd+Q</kbd>

Whatever solution we come up with should probably try to solve the "multikey sequence" problem too, i.e. how to present all of these unambiguously:

1. Non-shifted key: <kbd>Enter</kbd>
1. Normal keybinding: <kbd>Cmd+K</kbd>
1. Key sequence: <kbd>Cmd+K</kbd> <kbd>Right</kbd>
1. List of keybindings: <kbd>Ctrl+Q</kbd>, <kbd>Alt+F4</kbd>
1. List of key sequences: <kbd>Cmd+K</kbd> <kbd>Right</kbd>, <kbd>Cmd+K</kbd> <kbd>Left</kbd>

Or maybe we just need to pick a presentation system and then document it in the Flight Manual.
