### ISSUE TITLE
Standardize notation for various things

### ISSUE THREAD

**Issue by lee-dohm** [atom/flight-manual.atom.io#164]
The documentation in both the Flight Manual and the various `README` files are somewhat inconsistent. We should standardize the notation for the following things:

* [x] Package names &mdash; "status-bar", "Status Bar" or "status bar", see https://github.com/atom/line-ending-selector/issues/21
* [x] Keybinding notation &mdash; https://github.com/atom/docs/issues/161

Anything I've missed?

**Comment by simurai** [comment]
> Package names — "status-bar", "Status Bar" or "status bar"

I tend towards "status-bar", or even `status-bar`. It's how they get formatted in the settings or you can `apm install` it or paste it part of an URL etc.

**Comment by lee-dohm** [comment]
This has been fixed in the new [CONTRIBUTING guide](CONTRIBUTING.md).
