### ISSUE TITLE
'>' changed into '&gt;' on docs' website

### ISSUE THREAD

**Issue by imcaffrey** [atom/flight-manual.atom.io#173]
https://atom.io/docs/latest/behind-atom-keymaps-in-depth#keystroke-patterns
`'user:insert-date': (event) -&gt;`
It should be `'user:insert-date': (event) ->` as defined in this repo.

**Comment by gjtorikian** [comment]
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed.
