### ISSUE TITLE
Edit to the Linux section of the Flight Manual: mention that DEB/RPM installs do not auto-update

### ISSUE THREAD

**Issue by fusion809** [atom/flight-manual.atom.io#175]
Hi,

I would like to suggest an edit for [this section](https://atom.io/docs/latest/getting-started-installing-atom#atom-on-linux) of the flight manual, namely that there be a mention of the fact that Atom installed from Debian / RPM binaries provided by the Atom project do not automatically search for, and install available updates. It may also be worthwhile mentioning (if you are willing to look past the fact that these methods if installation/updating Atom are not officially supported by the Atom development team) that many distributions also come with their own Atom package, that usually receive regular updates. Examples of such distributions, include:

* Arch Linux, via the [Arch User Repository](https://aur.archlinux.org/packages/atom-editor)
* Fedora, via the [Mosquito Copr](https://copr.fedorainfracloud.org/coprs/mosquito/atom/). 
* Gentoo Linux, via the [`sabayon`](https://github.com/Sabayon/for-gentoo/blob/master/app-editors/atom) overlay. 
* Sabayon Linux, via the [Entropy Repositories](https://packages.sabayon.org/quicksearch?q=app-editors%2Fatom&x=0&y=0).
* Ubuntu, via the [WebUpd8 Team's PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/atom/). 

**EDIT:** I also noticed that the `$ rpm -i ...` line in the manual is wrong (it requires root privileges), it should be `$ sudo rpm -i ...` or `# rpm -i ...` It also can be modified to:

`$ sudo rpm -i https://github.com/atom/atom/archive/atom.x86_64.rpm`

because the `rpm` command has the ability to download the RPM binary and then install it, in the one command. 

Thanks for your time,
Brenton

**Comment by lee-dohm** [comment]
This is now fixed.
