### ISSUE TITLE
Add an Edit option for the Flight Manual (HTML)

### ISSUE THREAD

**Issue by fusion809** [atom/flight-manual.atom.io#176]
Hi,

When I was reading the Flight Manual and came up with the suggestion behind issue #175, I realized that adding an "Edit" option to each section of the flight manual (in HTML, it would be unrealistic to do this to the PDF copy of the flight manual, IMO) might be worthwhile. As it took me a while to find that this was the repo containing the Flight Manual (would have been longer if it weren't for the fact that @lee-dohm told me this was the repo I should start these issues at, which he mentioned [here](https://discuss.atom.io/t/shouldnt-there-be-an-edit-option-for-the-flight-manual-in-html-format/26926?u=fusion809) at discuss.atom.io), it also took me a while to realize that this was the repo I needed to make this edit suggestion at. Consequently, I think adding an "Edit" option would speed up the editing process for myself and many others that are interested in improving this manual. 

Thanks for your time,
Brenton

**Comment by simurai** [comment]
That's great suggestion. Maybe the title on the top/right could be a link to the right file on https://github.com/atom/docs. Or when you hover it, it could say `Title (edit)` or so.

![screen shot 2016-03-23 at 5 45 35 pm](https://cloud.githubusercontent.com/assets/378023/13980071/b1c382ec-f11f-11e5-8827-327b3235c408.png)

**Comment by lee-dohm** [comment]
The jekyllrb.com site has an "Improve this page" link at the top of every page:

<img width="704" alt="improve-this-page" src="https://cloud.githubusercontent.com/assets/1038121/13997832/2807e792-f0f1-11e5-9fe9-1682d077994d.png">

It's subtle and non-intrusive, but once you know it is there, it can be very useful. It links directly to the edit feature on the GitHub repo:

https://github.com/jekyll/jekyll/edit/master/site/_docs/index.md

**Comment by briandk** [comment]
I [had the exact same experience][1] as @fusion809, but I didn't realize it until I found this issue. Glad I checked the issues list :innocent:.

I'm totally on-board with any of the above suggestions. I also made a (terrible) mock-up of just adding a "Contribute!" button to the page footer. (Footers and headers are where I often look for links to the repository source of a page or project.)

<img width="1584" alt="2016-03-24 - add contribute button to github atom docs 03-24-16 12 15 58 am" src="https://cloud.githubusercontent.com/assets/330036/14008273/75ce202c-f155-11e5-8754-5c9066c8c900.png">

[1]: https://twitter.com/jllord/status/712027932378566656

**Comment by simurai** [comment]
@briandk Yes, bottom nav is also an option. Maybe there it would just link to the repo and not directly to each page.

**Comment by briandk** [comment]
@simurai - that's exactly what I was thinking: a bottom link that just led to the root of the docs repository. (I wasn't clever enough to think about a per-page solution like the Jekyll model :-)

**Comment by mnquintana** [comment]
Added in https://github.com/atom/flight-manual.atom.io/issues/181
