### ISSUE TITLE
no more ebook formats like PDF?

### ISSUE THREAD

**Issue by boyangwang** [atom/flight-manual.atom.io#186]
flight-manual used to auto generate ebook formats, which is very useful.

This is entirely gone? Is there any way to generate PDF from it now?

**Comment by lee-dohm** [comment]
To answer your question, there is no way to generate PDF or ebook formats from the new site. The amount of use they got didn't justify the maintenance burden of the various formats. If we can figure out a way to generate the alternate formats in a significantly more streamlined manner, we'll consider reinstating them.
