### ISSUE TITLE
Incomplete documentation in flight manual

### ISSUE THREAD

**Issue by reesjones** [atom/flight-manual.atom.io#192]
"The Flow" section is incomplete - currently just a bulleted list with a TODO at the end.

Location of incomplete documentation: 
[http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#the-flow](http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#the-flow)

**Edit**: The "Making our tests work" section is also incomplete.

Link: http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#making-our-tests-work

**Comment by lee-dohm** [comment]
Removed the glaringness of the omissions. The documentation is still incomplete, but it flows better now.
