### ISSUE TITLE
What is the "left panel" mentioned in Basic Customization?

### ISSUE THREAD

**Issue by nhinds** [atom/flight-manual.atom.io#195]
The [Basic Customization](http://flight-manual.atom.io/using-atom/sections/basic-customization/#_finding_the_language_scope_name) page ([basic-customization.asciidoc](https://github.com/atom/flight-manual.atom.io/blob/master/content/using-atom/sections/basic-customization.asciidoc)) has instructions to search for a language in the "left panel".

I cannot find any search box anywhere on the left side of the Settings pages. If I click into 'Packages', 'Themes' or 'Install', there is a search box in the main area of the screen. I suspect the search box on the 'Packages' screen is the one the documentation is referring to, as that allows me to find language packages.

Is there a left panel somewhere that I am missing, or have the docs not been updated after some sort of UI change?

Atom version: 1.7.3

**Comment by simurai** [comment]
It is the "Packages" in the nav. I think there used to be a search input under the nav. So the docs still refer to that.

This PR #197 should clarify it a bit more. Thanks for noticing.
