### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by ChrisChinchilla** [atom/flight-manual.atom.io#200]
I wouldn't mind stepping up… I am a technical writer and love Atom :)

**Comment by thomasjo** [comment]
Pull requests are welcome 🙇 
Please check out the [contribution guidelines](https://github.com/atom/flight-manual.atom.io/blob/master/CONTRIBUTING.md) first though.

**Comment by ChrisChinchilla** [comment]
OK @thomasjo you explicitly mention looking for maintainers in the read me though, so thought I'd reach out. I'll see what I can do.

**Comment by lee-dohm** [comment]
The text in the README states that there is no one maintainer that is in charge of the book, that is correct. We're definitely open to people that want to help make the manual better :grinning: Pull-requests are the way to start and we'll go from there.

Thanks very much for being willing to help!
