### ISSUE TITLE
Table of contents on the left is not highlighted for this link.

### ISSUE THREAD

**Issue by palaniraja** [atom/flight-manual.atom.io#202]
The default highlighting of TOC on the left is not visible only for this link.

http://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/

![screen shot 2016-06-12 at 10 30 28 pm](https://cloud.githubusercontent.com/assets/124864/15993945/51d34daa-30ed-11e6-8f1c-7bfb8a085854.png)

![screen shot 2016-06-12 at 10 30 40 pm](https://cloud.githubusercontent.com/assets/124864/15993946/51d4f5d8-30ed-11e6-8318-fd2c3eb9a09a.png)

**Comment by 50Wliu** [comment]
Confirmed.
