### ISSUE TITLE
The link to the Octicons usage is broken

### ISSUE THREAD

**Issue by platy11** [atom/flight-manual.atom.io#207]
The link [here](http://flight-manual.atom.io/hacking-atom/sections/iconography/) appears to be broken, and should probably be updated to either [this page](https://github.com/primer/octicons#install) or one like [this one](https://octicons.github.com/icon/mark-github/). We're getting a Travis CI issue like this:
![travis](https://cloud.githubusercontent.com/assets/17060983/16260598/7ef44a26-38ab-11e6-8a53-b99ee5e60cf5.PNG)

**Comment by simurai** [comment]
Let's link to https://octicons.github.com/icon/mark-github/. 👍  The other one doesn't say much about the markup usage.

**Comment by platy11** [comment]
@simurai Great, thanks!
