### ISSUE TITLE
Style Guide Missing

### ISSUE THREAD

**Issue by DamnedScholar** [atom/flight-manual.atom.io#208]
The [Iconography](http://flight-manual.atom.io/hacking-atom/sections/iconography/) section has a link to a style guide that no longer exists. Does anyone have the old style guide lying around? (Or is it somewhere in the history of this repo?) I would be willing to format it and submit a PR to put it back where it should be.

**Comment by simurai** [comment]
The Styleguide is actually part of Atom. Updated the link to http://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/#atom-styleguide with the shortcut/command.

Thanks for noticing. 🙇
