### ISSUE TITLE
Reasoning to Markdown switch

### ISSUE THREAD

**Issue by petko** [atom/flight-manual.atom.io#223]
Unfortunately, I can't find where this was discussed, but I notice that the manual transitioned to MD now. Is there a place where I can read about the reasoning for that? I am really curious, because this was one of the better Asciidoc projects until recently..

**Comment by lee-dohm** [comment]
* All other documentation Atom does is in Markdown
* Atom has great built-in support for Markdown and no support for Asciidoc out of the box
* The few things that Markdown doesn't have that Asciidoc provides, we were able to get from a simple `HtmlPipeline` plugin ... and even more besides
* The thing that the Atom Flight Manual really needed, OS-specific sections, neither Markdown nor Asciidoc provides without special tooling

So if we were going to need special tooling anyway, we might as well use a format that is more familiar to, accessible to and better supported for our users.
