### ISSUE TITLE
word-count example is a little bit outdated

### ISSUE THREAD

**Issue by Hammster** [atom/flight-manual.atom.io#225]
I just started reading through the flight-manual, and i was a bit confused that package.generator gave me a js/babel package instead of coffeescript. 

This is happening because of these changes atom/package-generator#36 which makes javascript the default, also the behaviour can be changed in the package options, maybe someone as new as me would not find it.

**Comment by lee-dohm** [comment]
Thanks for the feedback. We're aware that the example is outdated. I've been working hard to improve the Flight Manual the last week:

* https://github.com/atom/flight-manual.atom.io/pull/217
* https://github.com/atom/flight-manual.atom.io/pull/219

We'll be updating everything as we can.
