### ISSUE TITLE
Ambiguity in "Chapter 2: Using Atom - Snippets"

### ISSUE THREAD

**Issue by mzlogin** [atom/flight-manual.atom.io#241]
A paragraph in this sections is

> You can also use fuzzy search to filter this list down by typing in the selection box. Selecting one of them will execute the snippet where your cursor is (or multiple cursors are).

I cannot determine what's the second sentence saying.

It means 

**selecting one of them will execute the snippet, the snippet (or multiple snippets) you selected with your cursor in the waiting for the selection list**

or

**selecting one of them will execute the snippet, the snippet will insert to the position (or multiple positions) where your cursor in the editor**?

Any help is greatly appreciated.

**Comment by lee-dohm** [comment]
It means the second one. Selecting a snippet in the list will execute the snippet wherever there is a cursor.

**Comment by mzlogin** [comment]
@lee-dohm thx.
