### ISSUE TITLE
Building the docs for offline use is not easy for a novice

### ISSUE THREAD

**Issue by alecthegeek** [atom/flight-manual.atom.io#244]
The build instructions need some clarification and I had to to run  the following commands 1st:
- `gem install colorize -v '0.8.1`
- `gem install pry -v '0.10.4'`
- `gem install html-pipeline -v '2.2.4'`

This ticket is here to remind me to do something about it. Feel free to send me a rude email if this ticket gets to be more than 10 days old with with no update.

**Comment by alecthegeek** [comment]
I know nothing about Ruby dev but I am wondering if the above packages should be listed in the `Gemfile`?

**Comment by lee-dohm** [comment]
Did you use `script/bootstrap` and `script/server`? If you did, then you shouldn't have had to manually install anything. (Notice also that `script/bootstrap` installs gems into `vendor/gems` which might not be loaded if you don't use `script/server` or the requisite Bundler commands.)

**Comment by lee-dohm** [comment]
@alecthegeek Any more information you can share here on how you were running into the problems you mention?

**Comment by stephan-thelen** [comment]
Building fails:
```
script/bootstrap
==> Installing gem dependencies…
Your Ruby version is 2.3.3, but your Gemfile specified 2.2.3
```
or
```
rake
node_modules/gulp/bin/gulp.js build
rake aborted!
Command failed with status (127): [node_modules/gulp/bin/gulp.js build...]
/Users/[...]/projects/3rdparty/flight-manual.atom.io/Rakefile:26:in `block in <top (required)>'
```
