### ISSUE TITLE
Restyle platform picker

### ISSUE THREAD

**Issue by simurai** [atom/flight-manual.atom.io#249]
How about moving the "platform picker" next to the search input? Maybe like:

<img width="1085" alt="screen shot 2016-08-03 at 10 14 55 am" src="https://cloud.githubusercontent.com/assets/378023/17358728/ada0597c-5963-11e6-95b5-dfe43453ee52.png">

- It would make it look more like a global setting and not something you would change for every page.
- It would give a bit more breathing room to the title + "Improve this page"

My only concern is that it might look like it's part of the search. Like if you type something and then click one of the platform buttons and nothing happens. A separator line might make it more clear:

<img width="1023" alt="screen shot 2016-08-03 at 10 28 59 am" src="https://cloud.githubusercontent.com/assets/378023/17359067/4de7d760-5965-11e6-99eb-9f27d7113b90.png">

/cc @lee-dohm

**Comment by simurai** [comment]
Actually, there is still room in the top nav:

<img width="1084" alt="screen shot 2016-08-03 at 11 03 24 am" src="https://cloud.githubusercontent.com/assets/378023/17360124/3c32c836-596a-11e6-89b6-af3a58b078cb.png">

**Comment by bastilian** [comment]
It seems to be out of context in the nav-bar or next to the search box.

Maybe above the TOC to indicate the contents is viewed for that platform?

**Comment by simurai** [comment]
> Maybe above or below the TOC to indicate the contents is viewed for that platform?

![flight-manual](https://cloud.githubusercontent.com/assets/378023/17403995/6cc7b452-5a5a-11e6-937c-212648302ba7.png)

Yeah, although that could make it look like switching platforms would update the toc.

**Comment by bastilian** [comment]
I just played a bit with leaving it where it almost is already and restyle that part.
Maybe use the keyboard octicon instead of words.

![screen shot 2016-08-04 at 16 01 02](https://cloud.githubusercontent.com/assets/7757/17404627/b2d88af0-5a5c-11e6-8fee-ccb3580fe481.png)

I also removed the TOC title, I felt it is a bit redundant. with that both keyboard shortcut setting and "Improve this page" could even move into one line. both are features that don't need to be as prominent, or?

**Comment by bastilian** [comment]
Also, at the moment it is only shown on pages that have shortcuts, showing it on all might be better to be consistent.

**Comment by bastilian** [comment]
taking it back. that was an illusion. :D

**Comment by simurai** [comment]
I *think* it's not just for keyboard shortcuts, but can also be used to show different content. But let's try the "one line with an Octicon". 👍

**Comment by simurai** [comment]
Ok, there is now a PR #250.

Maybe we should wait with merging till @lee-dohm is back.
