### ISSUE TITLE
https://flight-manual.atom.io/ returning unsecured connection

### ISSUE THREAD

**Issue by veesa** [atom/flight-manual.atom.io#277]
I just visited https://flight-manual.atom.io/ and got an unsecured improperly configured notice.

I am using Firefox version 49.0.

**Comment by torn4dom4n** [comment]
You should use `http`, don't use `https`.

**Comment by marvinrichter** [comment]
@veesa is not the only one facing this certification error notification. just happend to me, too. And potentially will happen to every other Atom user because the link in the Atom menu `Help / Documentation` points to https://flight-manual.atom.io/

**Comment by lee-dohm** [comment]
@marvinrichter This is fixed in the latest Beta and will be in the next Stable release.
