### ISSUE TITLE
Miss Favico Icon

### ISSUE THREAD

**Issue by torn4dom4n** [atom/flight-manual.atom.io#295]
![miss-favico](https://cloud.githubusercontent.com/assets/16760489/20401861/0bb8d850-ad2d-11e6-95f4-9f9582671658.png)

**Comment by torn4dom4n** [comment]
![f12](https://cloud.githubusercontent.com/assets/16760489/20465087/00e35e34-af88-11e6-8544-87cb1ecb9b94.png)

**Comment by lee-dohm** [comment]
Thanks for letting us know!

**Comment by torn4dom4n** [comment]
@lee-dohm I reloaded but it still missing!
