### ISSUE TITLE
NaCl?

### ISSUE THREAD

**Issue by rugk** [atom/flight-manual.atom.io#302]
> In a browser, that would have required adventures with NaCl or Esprima.

http://flight-manual.atom.io/getting-started/sections/why-atom/#javascript-meet-c

NaCl is a crypto library. I don't think this fits into this sentence…

**Comment by lee-dohm** [comment]
It also refers to [Native Client](https://developer.chrome.com/native-client).

**Comment by rugk** [comment]
Maybe write it in brackets? 😄
