### ISSUE TITLE
Available snippet shortcut should be removed

### ISSUE THREAD

**Issue by astraldragon** [atom/flight-manual.atom.io#303]
Hi,

First time user here and was going through the docs.  Great docs by the way!  I noticed that the shortcut for viewing available snippets has been removed.  Was wondering if you wanted to remove the corresponding piece in the documentation?  I could fire up a quick PR for you.

**Comment by 50Wliu** [comment]
> I could fire up a quick PR for you.

Yes please!

**Comment by astraldragon** [comment]
There was a couple references to it.  Would you want to just pretend like it was never there?  Or would you want to put something in to reference the menu item? (Packages > Snippets > Available)

**Comment by 50Wliu** [comment]
I think referencing the menu item would be the best.  /cc @lee-dohm

**Comment by lee-dohm** [comment]
This was fixed in #312.
