### ISSUE TITLE
build fails for ruby 2.3.3 on OSX 10.11.6

### ISSUE THREAD

**Issue by bwagner** [atom/flight-manual.atom.io#310]
Building fails:
```
script/bootstrap
==> Installing gem dependencies…
Your Ruby version is 2.3.3, but your Gemfile specified 2.2.3
```
or
```
rake
node_modules/gulp/bin/gulp.js build
rake aborted!
Command failed with status (127): [node_modules/gulp/bin/gulp.js build...]
/Users/[...]/projects/3rdparty/flight-manual.atom.io/Rakefile:26:in `block in <top (required)>'
```

**Comment by lee-dohm** [comment]
Yes, we've verified that the combination of tools that we use work on Ruby v2.2.3. That's why we've specified a given version in our `Gemfile`. Do you still run into the same problem when building using Ruby v2.2.3?

**Comment by bwagner** [comment]
I'm sorry, in the meantime I changed the Gemfile to accept my newer version of Ruby and I had to manually install some of the gems (I believe html-proofer, html-pipeline, colorize, pry, bundler).
Now it's working.
