### ISSUE TITLE
Add a new section on contributing to packages

### ISSUE THREAD

**Issue by a7madgamal** [atom/flight-manual.atom.io#337]
I had to google for a while to figure out how to fix a simple issue for a package I use.
I expected a very clear and simple way to fork a github package, load it, debug and fix the issue to send the owner a PR. However, It wasn't as simple as I expected it to be.
A separate and clear section on this will help drive more contribution specially to first timers and noobz and might spare the pros some googling :)

**Comment by a7madgamal** [comment]
https://github.com/atom/atom/blob/master/docs/contributing-to-packages.md
after some serious googling I found this, I really think this should be copied or linked to in the flight-manual

**Comment by divayprakash** [comment]
Working on it!

**Comment by divayprakash** [comment]
@50Wliu Would an addition to chapter 3 containing the information be okay?

**Comment by 50Wliu** [comment]
Yes, that seems appropriate.

**Comment by divayprakash** [comment]
PR #345
