### ISSUE TITLE
api docs broken link

### ISSUE THREAD

**Issue by lemongrassnginger** [atom/flight-manual.atom.io#356]
apologies if this is not the correct place to report api docs errors, it's not obvious to me where else to report this

There's a broken link to `WorkspaceCenter` on [this page](https://atom.io/docs/api/v1.18.0/Workspace)

**Comment by 50Wliu** [comment]
Thanks for reporting @lemongrassnginger - I believe I've already fixed this and the docs should link correctly in Atom 1.20.0.
