### ISSUE TITLE
Usage of manual under Windows OS & Updating versions

### ISSUE THREAD

**Issue by danPadric** [atom/flight-manual.atom.io#362]
Hello.  _May this message find you well._

#### 1. Inside Windows
What is required to get the "project" to open in a Windows environment? Specifically for getting the "manual" to open and function on a nothing-loaded-except-Atom-PC. I suggest/request that these steps be discussed on the `read-me`.

Motivation: The `flight manual` is a good tool for beginners to get familiar with the Atom environment; specifically for coding for Atom inside Atom. So... who better to help expand the usability of this manual than a beginner. That means that it should be "easy" for a beginner to take step-by-step instructions and make the project run. _Even_ **without** prior knowledge of `bash` / `node.js` / `ruby` / `markdown`.

#### 2. Versions
Please consider updating the versions of Ruby and Gems utilised for this 'project'. Ruby V2.2.3 is not recommended for active service in my humble opinion.

Thank you for your attention. Thank you for your efforts.
\- Dan Padric

**Comment by lee-dohm** [comment]
> Specifically for getting the "manual" to open and function on a nothing-loaded-except-Atom-PC.

The steps are mentioned in the README under [Prerequisites](https://github.com/atom/flight-manual.atom.io#prerequisites), [Fetching dependencies](https://github.com/atom/flight-manual.atom.io#fetching-dependencies), and [Starting the site](https://github.com/atom/flight-manual.atom.io#starting-the-site).

> Please consider updating the versions of Ruby and Gems utilised for this 'project'.

The versions of Ruby and Gems used have to be compatible with the backend servers that generate the documentation automatically as well as be compatible with all platforms, including Windows.

Thanks for your feedback :+1:

**Comment by danPadric** [comment]
Sir,

Thank you for the response. I ask your patience.. it not education I request you focus your attention on.

> The steps are mentioned in the README under Prerequisites, Fetching dependencies, and Starting the site.

May I suggest you have a look with new eyes at the links you suggested.
The instructions -
`$ script/bootstrap`
and
`$ script/server`

Playing devil's advocate: Could these be executed anywhere? So if my terminal is in the root under `c:\`, those can be executed and the commands will 'know' that it is executed to handle the files that was cloned from document project.

Will someone that does not know ruby or node be able to follow these instructions blindly?

Regards.

**Comment by Ben3eeE** [comment]
> Could these be executed anywhere?

No. They would have to be executed inside your clone of this repository.

> Will someone that does not know ruby or node be able to follow these instructions blindly?

We will definitely review a PR that makes the steps more clear! An idea could be to merge this section with the contributing guide which explains more in detail how to contribute: https://github.com/atom/flight-manual.atom.io/blob/master/CONTRIBUTING.md#contributing-to-the-atom-flight-manual

**Comment by danPadric** [comment]
@Ben3eeE: I appreciate your reply, thank you.


> An idea could be to merge this section with the contributing guide which explains more in detail how to contribute

I agree with this idea. The steps in the provided link are now..

>     1. Fork this repository.
>     2. Download your fork. Refer to the GitHub Help site if you need more information.
>     3. Create a named feature branch. We use the standard GitHub Flow process.
>     4. Make a change to the content.
>     5. Push it to a branch.
>     6. Send us a Pull Request.

These make no mention of any ruby / node tasks as mentioned by the link given by @lee-dohm. Therefore detailed steps would be required there too in instructing people on how to bind (?) the manual for local review. I would suggest to add these instructions under a new sub-heading.

_The point is to make it easy for anyone to make contributions. Some users use Atom for non-coding writing and are not used to coding languages. My opinion is that they are also more likely to contribute to expanding the document._

Thank you for your consideration @lee-dohm and @Ben3eeE.

**Comment by lee-dohm** [comment]
@danPadric I completely understand the point you are making. I simply don't have the time to spend researching what it would take to build a step-by-step guide targeted at the complete beginner on how to get someone up-to-speed with all they need to know, across all platforms, to locally build and view the Flight Manual. I think it is a good idea. Unfortunately, there are higher priority things that are taking up the team's time. And I won't leave open an issue for something that the team won't have time or resources to complete in the near future.

If this is something that is important to you, I strongly recommend that you get involved and help out by contributing a pull request.

**Comment by danPadric** [comment]
@lee-dohm: I value your candour and respect your position in this matter.

Sadly it is a case of `chicken-and-egg`. Without instructions people like me cannot make positive contributions. Without growth in the community your team's task becomes heavier.

The other side of the coin is that your team cannot waste time babysitting the public. (stated as a hard fact)

I will not take up anymore of your team's time.
Sincerely - good luck.
