### ISSUE TITLE
cson snippet problem

### ISSUE THREAD

**Issue by mostafa6765** [atom/flight-manual.atom.io#372]
```cson
"zip->laravel[collections]":
    "prefix": "lcl-zip"
    "body": """
      use Illuminate\Http\Request;
    """
```

when lcl-zip it's make a proble all backslass don't access 
result ` use IlluminateHttpRequest;`

how can solve this type problem?

**Comment by 50Wliu** [comment]
Use `\\\\` instead of `\`.
