### ISSUE TITLE
Wrong param lists

### ISSUE THREAD

**Issue by yubaoquan** [atom/flight-manual.atom.io#375]
Some methods of workspace have wrong param list.
For example, method `observeTextEditors` only receive a callback as param, but in the [doc](https://atom.io/docs/api/v1.20.0/Workspace#instance-observeTextEditors), there is  another param named `editor` which is not declared in the [function](https://github.com/atom/atom/blob/v1.20.0/src/workspace.js#L619).

Please take a check, not limited in these methods: 
`observeTextEditors`
`observePaneItems`
`onDidStopChangingActivePaneItem`
`onDidChangeActiveTextEditor`
`observeActivePaneItem`
`onDidAddPane `
...

**Comment by 50Wliu** [comment]
Should be fixed in Atom 1.21 beta.  In addition, these type of issues bring on https://github.com/atom/atom.io.
