### ISSUE TITLE
Update the install guide on Windows

### ISSUE THREAD

**Issue by Ben3eeE** [atom/flight-manual.atom.io#379]
http://flight-manual.atom.io/getting-started/sections/installing-atom/#installing-atom-on-windows

This section states that the `Open With Atom` and `Open with...` associations are added by the installer. These associations are now controlled by settings in the settings-view:

![image](https://user-images.githubusercontent.com/1058982/31320404-56d61810-ac74-11e7-9a79-be9ccc88a075.png)

We need to revise this section to be up to date with the current defaults on Windows and add documentation for the System panel in the settings-view in a separate Windows-specific block.

PR that added the System Settings panel: https://github.com/atom/settings-view/pull/811

**Comment by Ben3eeE** [comment]
Hi @schalkneethling :wave:

Correct the task here is to update that section. I am not sure about removing the gif though. Maybe we can leave it in for now and remove the gif if it feels like it's too noisy? The current gif doesn't really add any value so maybe it would be good to remove it? What do you think?

**Comment by schalkneethling** [comment]
> can leave it in for now and remove the gif if it feels like it's too noisy? The current gif doesn't really add any value so maybe it would be good to remove it?

I would vote for it to be removed seeing that it adds no value.

**Comment by schalkneethling** [comment]
Pull request: https://github.com/atom/flight-manual.atom.io/pull/386
