### ISSUE TITLE
Order of sub categories in chapter

### ISSUE THREAD

**Issue by danPadric** [atom/flight-manual.atom.io#384]
Hello.
May this message find you well.

_I am slowly working through the Flight Manual. It is a great amount of information contained there. Much respect and thanks to the laddies and lassies involved._

< Looking at Chapter 2 - the order of the categories contained within. >
How about having all the mentioned of the core of Atom being listed first. That would mean that `Atom Packages` will be mentioned only later after how to navigate / edit / search and so on.

Panes and pending panes to me should be one category and mentioned earlier, perhaps after `moving in atom`. `Grammar` before autocomplete, snippets and folding.

Perhaps something like:
```text
CHAPTER 2
|- Moving in Atom
|- Atom Selections
|- Panes
|   |-- Pending Pane Items
|- Editing and Deleting Text
|- Find and Replace
|- Grammar
|- Snippets
|- Auto-complete
|- Folding
|- Writing in Atom
|- Atom Packages
|- Version Control in Atom
|- GitHub package
|- Basic Customization
|- Summary
```

The idea is to have one piece build onto another starting from the core functions and then branching out to customization and application specifics. Starting small and building to bigger.

That is my 2c worth of opinion.

**Comment by lee-dohm** [comment]
Thanks for the feedback. We definitely could use some cleanup and help on organizing things. I'll take a look when I get the chance :+1:
