### ISSUE TITLE
Missing significant features of github package

### ISSUE THREAD

**Issue by ginkgomzd** [atom/flight-manual.atom.io#396]
I've been using Atom for months now and only just stumbled upon how cool the GitHub package is, for two reasons...

The first reason was that there is no documentation of the "GitHub Tab" (Ctrl-Shift-9) in the Flight Manual. There should be at least a link to https://github.atom.io/ for "More Features"... or better yet, incorporate the feature showcase from that site in the flight manual.

The integration of diff viewing, staging, and merging is seriously useful and slick!

I will file an issue on the GitHub package for the second reason I had to stumble into the functionality.
That is, to get the full benefits, your project root and the github repo root must be the same.

I realize that most of the target audience will do this instinctively, but I think especially back-end developers will likely be working on projects with multiple repos and have a project root above the repos.
Or maybe it is just old-skool developers used to having a monolithic IDE. I'm getting used to opening an Atom window per-repo, and it ain't bad.

I think this baked-in assumption is limited to the GitHub package, and not Atom as a whole, but it might be worth mentioning in the Flight Manual.

Cheers

**Comment by Ben3eeE** [comment]
The GitHub package is documented in the flight-manual http://flight-manual.atom.io/using-atom/sections/github-package/. From what I can see this documentation mentions the same features as the https://github.atom.io/ site. Is there something in this documentation that you think is missing?

> I will file an issue on the GitHub package for the second reason I had to stumble into the functionality.
That is, to get the full benefits, your project root and the github repo root must be the same.

This sounds like https://github.com/atom/atom/issues/2203

**Comment by ginkgomzd** [comment]
err... right you are.
I guess I was skimming too fast. I was definitely looking at "Version Control in Atom" and not the very next page. Sorry.

Thanks!
