### ISSUE TITLE
Broken links/anchors

### ISSUE THREAD

**Issue by xfq** [atom/flight-manual.atom.io#40]
The [Figure 1-1](https://atom.io/docs/v0.189.0/ch00/_download_button) link in https://atom.io/docs/v0.189.0/getting-started-installing-atom goes to https://atom.io/docs/v0.189.0/ , but IMHO it should be a URL fragment (a name preceded by a hash mark, which specifies an ID within the current document) that links to a(n) image/figure below (in this case, images/linux-downloads.png).

It seems that the link is actually https://atom.io/docs/v0.189.0/ch00/_download_button , but redirects (correct me if I'm wrong) me (or the browser) to https://atom.io/docs/v0.189.0/ .

I have tried Firefox 37.0, Google Chrome 41.0.2272.118, Opera 28.0.1750.48, and Safari 8.0.4 on OS X 10.10.2. This issue can be reproduced.

**Comment by xfq** [comment]
Actually, most (if not all) xref links (`<< ... >>`) don't work. For example, see all xref links on https://atom.io/docs/v0.189.0/getting-started-atom-basics .

**Comment by schacon** [comment]
Huh, you're right. That worked previously, I'll look into it. Thanks!

**Comment by gjtorikian** [comment]
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed.
