### ISSUE TITLE
Alphabetical list of terms

### ISSUE THREAD

**Issue by xfq** [atom/flight-manual.atom.io#41]
It'd be nice to have an alphabetical list of terms in the documentation, with and/or without definitions. The list can be included as an appendix for the Atom Flight Manual, and we can link to the list [here](https://github.com/atom/docs/blob/51a7897458592dc638e27a4a622f88de27ce21d2/book/01-introduction/sections/03-basics.asc#basic-terminology). To me, this kind of lists are often more useful than search engines because they are very selective, and search engines may miss relevant information if the information is not phrased in exactly the way I expect.

Here's an example for a list of terms with definitions: https://www.gnu.org/software/emacs/manual/html_node/emacs/Glossary.html#Glossary

Here's an example for a list of terms without definitions (but with links): https://www.gnu.org/software/emacs/manual/html_node/emacs/Concept-Index.html#Concept-Index

**Comment by lee-dohm** [comment]
We have a [glossary appendix](http://flight-manual.atom.io/resources/sections/glossary/) now.
