### ISSUE TITLE
Use HTTPS by default

### ISSUE THREAD

**Issue by 50Wliu** [atom/flight-manual.atom.io#437]
There _is_ an HTTPS version of the Flight Manual available, so ideally all requests to the HTTP version should redirect to the HTTPS version instead 🙂.  Right now if you just type in `flight-manual.atom.io` you'll be sent to the HTTP version, which means Chrome will give a "Not Secure" warning when searching for something.

**Comment by 50Wliu** [comment]
Fixed, thanks @lee-dohm!

**Comment by lee-dohm** [comment]
You're welcome @50Wliu :grinning: Thanks for the reminder.
