### ISSUE TITLE
Contradictory info on default keybindings for Movement and Selection Commands

### ISSUE THREAD

**Issue by Botmasher** [atom/flight-manual.atom.io#465]
According to [Additional Movement and Selection Commands](https://flight-manual.atom.io/using-atom/sections/moving-in-atom/#additional-movement-and-selection-commands), the command `editor:move-to-beginning-of-screen-line` has no keybinding by default.

> the command `editor:move-to-beginning-of-screen-line` is available in the command palette, but it's not bound to any key combination

At the end of that subsection, the same command is listed as having a default keyboard shortcut:

> Here's a list of Movement and Selection Commands that have a keyboard shortcut by default
> ```
> ...
> editor:move-to-beginning-of-screen-line
> ...
> ```

Judging from a fresh install of atom and the atom [keymaps](https://github.com/atom/atom/tree/master/keymaps), it seems like it does not have a default keybinding.

That whole list is mixed in terms of default keybindings. For example, the command `editor:select-to-beginning-of-word` is bound by default, while `editor:select-to-beginning-of-line` is not. Was this meant as a list of movement commands that don't have default keybindings?

I'm happy to make a PR with the update once I understand the intent.

**Comment by rsese** [comment]
Hmmm, yeah - section was added in https://github.com/atom/flight-manual.atom.io/pull/426, I think the list was supposed to be commands with no keybindings yeah @ungb?

**Comment by ungb** [comment]
that is correct. Good catch, I can submit a PR sometime tomorrow, or if someone can get to it before me!

**Comment by Botmasher** [comment]
@ungb Thanks for confirming that - I had the chance to open a pull request [here](https://github.com/atom/flight-manual.atom.io/pull/467).
