### ISSUE TITLE
Add "Updating Atom" section

### ISSUE THREAD

**Issue by kuychaco** [atom/flight-manual.atom.io#489]
This will serve as a handy resource to point people to. For example, when we release hotfixes for security vulnerabilities we want to get people's Atom version updated asap.

Example contents:

Atom checks for updates every 4-6 hours on Windows and macOS, but they can update anytime by clicking "Help -> Check for updates" on Windows or "Atom (Beta) -> Check for updates" on macOS

For Linux they will have to update manually by downloading the latest release from atom.io if they aren't using our official package repositories: https://flight-manual.atom.io/getting-started/sections/installing-atom/#installing-atom-on-linux

/cc @daviwil

**Comment by AustinVockrodt** [comment]
Has anyone contributed to this section yet? If not I'd be happy to give it a go.

**Comment by rsese** [comment]
Thanks @AustinVockrodt - no one has opened a pull request for this as far as I know (and after a quick skim of the open pull requests).

**Comment by AustinVockrodt** [comment]
Hey @rsese, I submitted a pull request for the added section. It's currently saying that the Travis CI build failed. Not sure if I made a mistake somewhere along the pull request process or if it is something else.

**Comment by rsese** [comment]
Thanks @AustinVockrodt, we'll take a look as soon as we can :+1:
