### ISSUE TITLE
Document Shadow DOM usage for styles.less

### ISSUE THREAD

**Issue by mnquintana** [atom/flight-manual.atom.io#56]
From https://github.com/atom/atom/issues/4420 and https://github.com/atom/atom/issues/4420#issuecomment-98966377

We should explicitly document the need to reach inside the Shadow DOM to style certain elements in `styles.less`.

**Comment by chibicode** [comment]
:+1:

**Comment by jamesjrg** [comment]
well this took me like 45 minutes to figure out...

**Comment by simurai** [comment]
Added a sub-section about the need for `atom-text-editor::shadow` in PR #141. [Rendered text](https://github.com/atom/docs/blob/sm-style-tweaks/book/02-using-atom/sections/06-customizing.asc#styling-the-editor)

@jamesjrg would this make it more clear?

**Comment by jamesjrg** [comment]
yup looks much clearer in the PR thanks!
