### ISSUE TITLE
Documentation website is very slow

### ISSUE THREAD

**Issue by francoislaberge** [atom/flight-manual.atom.io#59]
hi,

The [atom.io](http://atom.io/) website loads pages very slow, is there anything that can be done about that? It makes looking for documentation tedious.

Thanks!
Francois

**Comment by mnquintana** [comment]
cc @thedaniel

**Comment by lee-dohm** [comment]
@francoislaberge Do you have any data on this? Like a HAR log? I just tried clean refreshes a few times and, while not fast, it was between 1-2 seconds from start to finish.

**Comment by francoislaberge** [comment]
I can never get a faster than 2 second load time. Here's my HAR:
https://gist.github.com/francoislaberge/53d5afe67832b09c07e6

Maybe I'm being too first world, but I look stuff up so much that the delay starts to grate. Especially when usually I have to click a few times to get to where I want.

For comparison, see how fast Facebook React's Documentation loads, or any page on their site:
http://facebook.github.io/react/docs/getting-started.html

Thanks for looking into this guys!

**Comment by mnquintana** [comment]
This is what I got for https://atom.io/docs/api/v0.199.0/TextEditor: https://gist.github.com/mnquintana/5e793e70c75a920a9bbf

~3 seconds total. Interestingly, even enabling caching only shaved the load time down to ~2.2 seconds.

I have noticed though that atom.io/docs/* seems to *feel* slow.

**Comment by izuzak** [comment]
I'm seeing lots times on the docs site above 3-4 seconds as well. :watch: Wish it loaded faster, yeah :+1:

**Comment by gjtorikian** [comment]
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed.
