### ISSUE TITLE
Mobi version crashes Kindle for Mac

### ISSUE THREAD

**Issue by lee-dohm** [atom/flight-manual.atom.io#63]
I haven't tried it on Kindle for other platforms.

## Steps to Reproduce

1. Open a Terminal window
1. Follow the build instructions to generate the Mobi format
1. Enter `open atom.mobi`

**Expected:** Kindle for Mac to open and display the eBook
**Actual:** Kindle for Mac opens and pretty quickly closes again

Once the above is completed, the broken eBook is in your Kindle library:

1. Launch Kindle for Mac
1. Navigate to the Kindle Library
1. Click the Atom Flight Manual eBook

**Expected:** eBook opens
**Actual:** Kindle for Mac crashes

**Comment by gjtorikian** [comment]
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed in that we no longer support this for now.
