### ISSUE TITLE
Intro sections for each chapter are missing from online version

### ISSUE THREAD

**Issue by izuzak** [atom/flight-manual.atom.io#67]
For example, the introduction into Chapter 2 and the summary are in [this file](https://github.com/atom/docs/blob/master/book/02-using-atom/1-using-atom.asc).

The HTML version generated locally using `bundle exec rake book:build` contains that content:

![screen shot 2015-05-30 at 17 07 26](https://cloud.githubusercontent.com/assets/38924/7897886/8b4bc8a2-06ee-11e5-9421-4a040721a206.png)

But the online version (on atom.io) [doesn't](https://atom.io/docs/v0.204.0/) -- the section is not clickable in the TOC:

![screen shot 2015-05-30 at 17 09 07](https://cloud.githubusercontent.com/assets/38924/7897889/a3e1b372-06ee-11e5-8950-3e9231f57133.png)

cc @schacon @thedaniel @benogle for :thought_balloon:

**Comment by izuzak** [comment]
I was wrong. The introduction section for a chapter is shown on the page for the first sub-chapter:

![screen shot 2015-06-01 at 00 45 51](https://cloud.githubusercontent.com/assets/38924/7904335/97f9863e-07f7-11e5-9b82-6a8162b2ecc2.png)

However, it seems as if only the first paragraph from the introduction is shown on the page. For example, [the introduction for chapter 2 has two paragraphs](https://github.com/atom/docs/blob/10f5746167db4e01784ae20351496ea7e64abef7/book/02-using-atom/1-using-atom.asc), and the page on atom.io shows only one (as shown above).

And I still think that introduction should be shown on a separate page for the chapter, not bundled with the first sub-chapter, as it is currently.

**Comment by lee-dohm** [comment]
This has been fixed in the process of platformification recently undertaken.
