### ISSUE TITLE
Web version has no styling for `WARNING` or `CAUTION`

### ISSUE THREAD

**Issue by mnquintana** [atom/flight-manual.atom.io#79]
Example from https://atom.io/docs/latest/behind-atom-maintaining-your-packages#rename-your-package

### Source
```asciidoc
WARNING: Once a package name has been used, it cannot be re-used by another package even if the original package is unpublished.
```

### PDF
![screenshot 2015-06-19 14 04 02](https://cloud.githubusercontent.com/assets/823545/8259656/2121f692-168c-11e5-9a20-e16821cf41a7.png)

### asciidoc-preview
![screenshot 2015-06-19 14 06 08](https://cloud.githubusercontent.com/assets/823545/8259682/5b1c5356-168c-11e5-8be4-7cf526bb34b2.png)

### Web
![screenshot 2015-06-19 14 09 23](https://cloud.githubusercontent.com/assets/823545/8259741/cf17c3c6-168c-11e5-98f8-998ac67369fc.png)

**Comment by simurai** [comment]
Somehow this got added: http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/ Maybe un-intentionally. :v:
