### ISSUE TITLE
HTML download contains most files in repo

### ISSUE THREAD

**Issue by mnquintana** [atom/flight-manual.atom.io#80]
![screenshot 2015-06-21 06 58 20](https://cloud.githubusercontent.com/assets/823545/8271390/2880da68-17e3-11e5-8ce5-d061ae0e7947.png)

There should probably only be the `book/`, `theme/html/*.css` and HTML files in this download (although for portability it might be nice if the CSS were inlined in the HTML files).

**Comment by lee-dohm** [comment]
Since there is no longer an HTML download, this is no longer applicable.
