### ISSUE TITLE
Sometimes the docs site is not generated correctly and causes cross-chapter links not to work

### ISSUE THREAD

**Issue by izuzak** [atom/flight-manual.atom.io#94]
This is a continuation of https://github.com/atom/docs/pull/86 where @rachelmyers. 

To summarize: if you visit [this page](https://atom.io/docs/v1.0.1/hacking-atom-the-init-file) of the docs for version 1.0.1, then clicking the “Package: Word Count” link takes you to https://atom.io/docs/v1.0.1/ instead of to https://atom.io/docs/v1.0.1/hacking-atom-package-word-count, even though that page exists. This doesn't happen for version 1.0.0 nor 1.0.2. 

The troubling part of all of this is -- there was no indication that something was broken neither when content-change PRs were merged in this repository nor when a new version of Atom was published. In other words -- we had no idea this happened or why until the issue was reported by a user. And that's scary because it might happen again.

@gjtorikian and I were looking into this a bit today, and this seems to be related to the redirection which happens when the link is clicked. In the version of the docs which has the described problem, the site redirects to the wrong location for some reason. This made us suspect that the site wasn't generated correctly and it wasn't a problem in the content in this repository. We also looked at the webhook deliveries to Atlas made to from this repository and noticed some 500 and 404 statuses, but not sure if this is related.

cc @schacon @thedaniel @benogle

**Comment by izuzak** [comment]
Also wanted to cross-link to an older issue with "broken" links, which is still present in the latest version of the docs site:

https://github.com/atom/docs/issues/40

If you visit https://atom.io/docs/latest/getting-started-installing-atom and click the "Figure 1-1" link -- you see the same behavior: you're taken to https://atom.io/docs/v1.0.2/.

**Comment by rachelmyers** [comment]
> In the version of the docs which has the described problem, the site redirects to the wrong location for some reason. This made us suspect that the site wasn't generated correctly and it wasn't a problem in the content in this repository.

That's interesting. Just for my understanding, we use Atlas to convert the Asciidoc to HTML (and other formats)? And that's not vendored inside the project, it's an API we call when we build the book? 

Do you think the API changed out from under us, or so you think we're doing something wrong when we build it??

**Comment by dcarral** [comment]
Even without knowing where this bug exactly comes from, a pair of questions came to my mind after noticing the issue: 

What does Atlas provide? Is there any good reason to use it? (fwiw, googling 'atlas asciidoctor' points to this [interesting discussion @ asciidoctor forums](http://discuss.asciidoctor.org/O-Reilly-Atlas-td872.html))

**Comment by gjtorikian** [comment]
As we've moved off of Atlas in https://github.com/atom/flight-manual.atom.io/pull/158, this should be fixed.

**Comment by dcarral** [comment]
Nice to finally hear this :) Thanks for updating the thread @gjtorikian!
